[tool.poetry]
name = "domain"
version = "0.1.1"
description = ""
authors = ["Matt Davies <matt@filament.so>"]

[tool.poetry.dependencies]
python = "^3.8"
pantam = "^1.0.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
