[tool.poetry]
name = "event"
version = "0.1.0"
description = ""
authors = ["Matt Davies <matt@teamdavies.co.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
pantam = "^0.0.1-alpha.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
