name: Build Package

on:
  release:
    types: [created]

jobs:
  publish-after-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: snok/install-poetry@v1.1.2
      - run: poetry install
      - run: poetry run pytest
      - name: Publish package
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{secrets.pypi_token}}
