name: Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v1
      - uses: dschep/install-poetry-action@v1.3
        with:
          create_virtualenvs: true
      - run: poetry install
      - run: poetry run pytest
