name: Pull Requests

on:
  pull_request:
    branches: [ master ]

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.2
          poetry_version: 1.0.10
          args: install
      - name: Run pytest
        uses: abatilo/actions-poetry@v1.5.0
        with:
          python_version: 3.8.2
          poetry_version: 1.0.10
          args: run python pytest
